title: 5prime
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.5pri.me" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dara O'Connor # add your name
author-img: Minimal.png # add your photo
about-author: I'm a translator and copywriter based in Montr√©al, Quebec. <br>I love languages and dabble in natural language processing. <br><br><strong>Fun Fact!</strong> Before studying translation, I studied biology and bioinformatics and worked in the biomedical sciences.

social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-email: dara@5pri.me # add your Email address
social-linkedin: # add your Linkedin handle
social-github: # add your Github handle

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
